In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import cvxpy as cvx
%matplotlib inline

## 1) Write down RMP 

$$ \min \sum_{j=1}^3 x_j \\
s.t.\ x_1[40, 0, 0]^T + x_2[0, 16, 0]^T + x_3[0, 0, 12]^T = [150, 100, 80]^T\\
x \geq 0$$

## 2) Solve RMP in CVX

In [2]:
A = np.array([[40, 0, 0],
             [0, 16, 0],
             [0, 0, 12]])
b = np.array([150, 100, 80])
x = cvx.Variable((3,), nonneg = True)

cons = [A * x == b]

obj = cvx.Minimize(cvx.sum(x))
problem = cvx.Problem(obj, cons)
problem.solve()


print('Optimal:', problem.value, 'Vars:', x.value)
print('B:', A, '\n', 'B^-1:',np.linalg.inv(A), '\n''Dual Sol:', np.ones(3).dot(np.linalg.inv(A)))


Optimal: 16.6666666667 Vars: [ 3.75        6.25        6.66666667]
B: [[40  0  0]
 [ 0 16  0]
 [ 0  0 12]] 
 B^-1: [[ 0.025       0.          0.        ]
 [ 0.          0.0625      0.        ]
 [ 0.          0.          0.08333333]] 
Dual Sol: [ 0.025       0.0625      0.08333333]


## 3) Write down pricing problem

$$ \max \hat{y}^Ta \\
s.t.\ [5, 12, 16]^Ta \leq 200 \\
a \geq 0,\ a \in \mathbb{Z}$$

## 4) Solve pricing problem in CVX

In [ ]:
y_hat = np.array([ 0.025,       0.0625,      0.08333333])
a = cvx.((3,), integer = True)

cons = [np.array([5, 12, 16], dtype=int) * a <= 200,
       a >= 0]

obj = cvx.Maximize(y_hat * a)
problem = cvx.Problem(obj, cons)
problem.solve()

In [5]:
a.value

array([ 3.4060292 ,  7.59814807,  5.73393702])